In [3]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis=0) # esse axis significa que você quer que o Python some verticalmente, para o eixo horizontal seria axis=1

print(cal)

[ 59.  239.  155.4  76.9]


In [8]:
percentage = 100*A/cal.reshape(1,4) # exemplo de brodcasting em Python, a matriz se ajusta para ter o tamanho 
# adequado para fazer uma determinada operação 
# onde você pega a matriz A 3x4 e divide por uma matriz 1x4. O comando reshape é uma constante multiplicadora
# é usado para ter certeza que sua matriz em o tamanho que você precise que ela tenha

print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
